- name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: tuition-platform      
          environment_name: epl-tutors-env          
          version_label: "ver-${{ github.sha }}"
          region: eu-north-1
          deployment_package: deploy.zip